# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://eitanlees.github.io',
                'git_url': 'https://github.com/eitanlees/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.mymod': { 'nbdev_hello_world.mymod.foo': ('mymod.html#foo', 'nbdev_hello_world/mymod.py'),
                                         'nbdev_hello_world.mymod.say_hello': ('mymod.html#say_hello', 'nbdev_hello_world/mymod.py')}}}
